services:
  api:
    build: .
    image: ayfri/ia-cloud-1:latest
    ports:
      - "${PORT:-8050}:8050"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - INITIAL_RUN_ID=${INITIAL_RUN_ID}
    volumes:
      - ./mlruns:/app/mlruns
    depends_on:
      - mlflow_server

  mlflow_server:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /app/mlruns --host 0.0.0.0
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/mlflow.db
